### ISSUE TITLE
New Trace leve in logrus

### ISSUE THREAD

**Issue by dgsb** [kpfaulkner/azuretablehook#1]
Hello, I'm just opening this issue to let you know, the next release of logrus (v1.2.0) will add a new trace level named Trace below Debug.
Here is the PR for reference sirupsen/logrus#844
You may/want to take into account this new level.

**Comment by kpfaulkner** [comment]
Thanks, but nothing required for azuretablehook based on what I've read. (due to the level purely being a field in a column we populate).

Thanks for the heads up though.
